name: Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: DevFabricio13
          gif_out_path: ./output/github-contribution-grid-snake.svg
          svg_out_path: ./output/github-contribution-grid-snake.svg
      - name: push to origin
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./output/github-contribution-grid-snake.svg
          git diff --staged --quiet || git commit -m "Generate Snake Game"
          git push
